services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - env/local/db.env
    networks:
      tco:


volumes:
  db_data:

networks:
  tco: